# Generated by Django 5.1.3 on 2024-12-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='uploads/images')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='uploads/images')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='uploads/images')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                   ('videoUrl',models.URLField(blank=True, null=True) ),
            ],
        ),
    ]
