# Generated by Django 5.1.3 on 2025-01-22 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_contact_genre_user_remove_movie_image3_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='category',
            new_name='categoryId',
        ),
    ]
