# Generated by Django 5.1.5 on 2025-01-22 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_contact_genre_user_remove_movie_image3_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
