# Generated by Django 5.1.3 on 2024-12-18 09:27

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=150)),
                ('lName', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='movie',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.UniqueImageName()),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.UniqueImageName()),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.UniqueImageName()),
        ),
    ]
