# Generated by Django 5.1.3 on 2024-12-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_alter_movie_image1_alter_movie_image2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('inquiry', models.TextField()),
                ('contact_number', models.CharField(max_length=15)),
            ],
        ),
    ]
