# Generated by Django 5.1.3 on 2025-01-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='image3',
        ),
        migrations.AddField(
            model_name='movie',
            name='movieTrailer',
            field=models.CharField(default='default-trailer-url', max_length=300),
            preserve_default=False,
        ),
    ]
