# Generated by Django 5.1.3 on 2025-01-20 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_genre_moviegenre'),
        ('api', '0005_remove_movie_image3_movie_movietrailer'),
    ]

    operations = [
    ]
