# Generated by Django 5.1.5 on 2025-01-21 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_genre_moviegenre'),
        ('api', '0005_remove_movie_image3_movie_movietrailer'),
    ]

    operations = [
    ]
